// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SettlementsColumns holds the columns for the "settlements" table.
	SettlementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "owner", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "survival_limit", Type: field.TypeInt, Default: 0},
		{Name: "departing_survival", Type: field.TypeInt, Default: 0},
		{Name: "collective_cognition", Type: field.TypeInt, Default: 0},
		{Name: "current_year", Type: field.TypeInt, Default: 0},
	}
	// SettlementsTable holds the schema information for the "settlements" table.
	SettlementsTable = &schema.Table{
		Name:       "settlements",
		Columns:    SettlementsColumns,
		PrimaryKey: []*schema.Column{SettlementsColumns[0]},
	}
	// SurvivorsColumns holds the columns for the "survivors" table.
	SurvivorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "born", Type: field.TypeInt, Default: 0},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"M", "F"}, Default: "F"},
		{Name: "huntxp", Type: field.TypeInt, Default: 0},
		{Name: "survival", Type: field.TypeInt, Default: 0},
		{Name: "movement", Type: field.TypeInt, Default: 5},
		{Name: "accuracy", Type: field.TypeInt, Default: 0},
		{Name: "strength", Type: field.TypeInt, Default: 0},
		{Name: "evasion", Type: field.TypeInt, Default: 0},
		{Name: "luck", Type: field.TypeInt, Default: 0},
		{Name: "speed", Type: field.TypeInt, Default: 0},
		{Name: "systemicpressure", Type: field.TypeInt, Default: 0},
		{Name: "torment", Type: field.TypeInt, Default: 0},
		{Name: "insanity", Type: field.TypeInt, Default: 0},
		{Name: "lumi", Type: field.TypeInt, Default: 0},
		{Name: "courage", Type: field.TypeInt, Default: 0},
		{Name: "understanding", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"alive", "dead", "ceased_to_exist", "retired", "skip_hunt"}, Default: "alive"},
		{Name: "status_change_year", Type: field.TypeInt, Default: 0},
		{Name: "settlement_id", Type: field.TypeInt, Nullable: true},
	}
	// SurvivorsTable holds the schema information for the "survivors" table.
	SurvivorsTable = &schema.Table{
		Name:       "survivors",
		Columns:    SurvivorsColumns,
		PrimaryKey: []*schema.Column{SurvivorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "survivors_settlements_population",
				Columns:    []*schema.Column{SurvivorsColumns[20]},
				RefColumns: []*schema.Column{SettlementsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SettlementsTable,
		SurvivorsTable,
	}
)

func init() {
	SurvivorsTable.ForeignKeys[0].RefTable = SettlementsTable
}
