// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (s *Settlement) Population(ctx context.Context) (result []*Survivor, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = s.NamedPopulation(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = s.Edges.PopulationOrErr()
	}
	if IsNotLoaded(err) {
		result, err = s.QueryPopulation().All(ctx)
	}
	return result, err
}

func (s *Survivor) Settlement(ctx context.Context) (*Settlement, error) {
	result, err := s.Edges.SettlementOrErr()
	if IsNotLoaded(err) {
		result, err = s.QuerySettlement().Only(ctx)
	}
	return result, MaskNotFound(err)
}
