// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Settlement is the predicate function for settlement builders.
type Settlement func(*sql.Selector)

// Survivor is the predicate function for survivor builders.
type Survivor func(*sql.Selector)
